version: '3.3'

services:

  liberty:
    build: ../liberty-container
    ports: 
      - "4005:5005"
    networks: 
      - backend

  frontend_app:
    build: ../apache-container/
    ports:
      - "80:80"
    depends_on:
      - autorization
    networks: 
      - backend

  
  autorization:
    container_name: authorization
    build: ../NodeJS_container
    ports:
      - "8080:8080"
    networks: 
      - backend

  db:
    # image: mysql
    build: ../sql-container
    volumes:
      - "./mysql_data:/var/lib/mysql"
    container_name: mysql1
    # networks: 
    #   - files-mysql
    # # command: --default-authentication-plugin=mysql_native_password
    # restart: always
    ports:
      - "3306:3306"
    networks: 
      - backend
  
  db-jdbc:
    build: ../manage
    ports:
      - "9080:9080"
    # depends_on:
    #   - db
    networks: 
      - backend

networks: 
  backend:
    driver: bridge

  # admin:    
  #   image: adminer   
  #   restart: always 
  #   ports:      
  #     - "9080:9080"