version: '3.3'

services:

  frontend:
    container_name: frontend
    build: ../apache-container/
    hostname: frontend:80
    ports:
      - "80:80"
    depends_on:
      - db-jdbc
      - authorization
    networks: 
      - backend

  authorization:
    container_name: authorization
    build: ../NodeJS_container
    ports:
      - "8001:3001"
    networks: 
      - backend

  db:
    build: ../sql-container
    volumes:
      - "./mysql_data:/var/lib/mysql"
    container_name: mysql1
    # # command: --default-authentication-plugin=mysql_native_password
    # restart: always
    ports:
      - "3306:3306"
    networks: 
      - backend
  
  db-jdbc:
    build: ../manage
    ports:
      - "9080:9080"
    container_name: dbjdbc
    depends_on:
      - db
    networks: 
      - backend

networks: 
  backend:
    driver: bridge
